{{- if and .Values.ksocRuntime.enabled .Values.metacollector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: k8s-metacollector
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ksoc-k8s-metacollector
    app.kubernetes.io/instance: k8s-metacollector
spec:
  type: ClusterIP
  ports:
    - name: broker-grpc
      port: 45000
      protocol: TCP
      targetPort: broker-grpc
    - name: health-probe
      port: 8081
      protocol: TCP
      targetPort: health-probe
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: ksoc-k8s-metacollector
    app.kubernetes.io/instance: k8s-metacollector
{{- end }}
