{{- if and .Values.ksocRuntime.enabled .Values.metacollector.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksoc-k8s-metacollector
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ksoc-k8s-metacollector
    app.kubernetes.io/instance: k8s-metacollector
{{- end }}
