{{ if and (not (or .Values.ksoc.accessKeySecretNameOverride)) (or (and .Values.ksoc.base64AccessKeyId .Values.ksoc.base64SecretKey) .Values.ksoc.apiKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: ksoc-access-key
  namespace: {{ .Release.Namespace }}
  labels:
    maintained_by: ksoc
data:
  access-key-id: {{ if .Values.ksoc.base64AccessKeyId }}{{ .Values.ksoc.base64AccessKeyId }}{{ else }}{{ (split ":" .Values.ksoc.apiKey)._0 }}{{- end }}
  secret-key: {{ if .Values.ksoc.base64SecretKey }}{{ .Values.ksoc.base64SecretKey }}{{ else }}{{ (split ":" .Values.ksoc.apiKey)._1 }}{{- end }}
{{ end }}
