apiVersion: v2
name: ksoc-plugins
version: 1.0.36
description: A Helm chart to run the KSOC plugins
home: https://ksoc.com
icon: https://ksoc.com/hubfs/Ksoc-logo.svg
keywords:
  - kubernetes
  - helm
  - opa
  - ksoc
maintainers:
  - name: KSOC Engineering
    email: engineering@ksoc.com
annotations:
  artifacthub.io/category: security
  # Possible kind options are added, changed, deprecated, removed, fixed and security.
  artifacthub.io/changes: |
    - kind: changed
      description: Updated the ksoc-sbom image to v1.0.2 to fix a medium vulnerability(GHSA-jq35-85cj-fj4p). See https://github.com/moby/moby/security/advisories/GHSA-jq35-85cj-fj4p
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/links: |
    - name: source
      url: https://github.com/ksoclabs/ksoc-plugins-helm-chart
    - name: support
      url: https://github.com/ksoclabs/ksoc-plugins-helm-chart/issues
dependencies:
  - name: falco
    repository: https://falcosecurity.github.io/charts
    version: 3.8.4
    condition: ksocRuntime.enabled
