apiVersion: v2
name: ksoc-plugins
version: 1.0.35
description: A Helm chart to run the KSOC plugins
home: https://ksoc.com
icon: https://ksoc.com/hubfs/Ksoc-logo.svg
keywords:
  - kubernetes
  - helm
  - opa
  - ksoc
maintainers:
  - name: KSOC Engineering
    email: engineering@ksoc.com
annotations:
  artifacthub.io/category: security
  # Possible kind options are added, changed, deprecated, removed, fixed and security.
  artifacthub.io/changes: |
    - kind: added
      description: Added custom rules to generate file access and executable profiles to show reachable package vulnerabilities.
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/links: |
    - name: source
      url: https://github.com/ksoclabs/ksoc-plugins-helm-chart
    - name: support
      url: https://github.com/ksoclabs/ksoc-plugins-helm-chart/issues
dependencies:
  - name: falco
    repository: https://falcosecurity.github.io/charts
    version: 3.8.4
    condition: ksocRuntime.enabled
