{{- if .Values.ksocRuntime.enabled  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.falco.fullnameOverride }}
rules:
- apiGroups:
  - extensions
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - replicationcontrollers
  - replicasets
  - services
  - daemonsets
  - deployments
  - events
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /healthz
  - /healthz/*
  verbs:
  - get
{{- end }}
