{{- if .Values.ksocRuntime.detectReachableVulnerabilities }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ksoc-runtime-profile-configuration
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: ksoc-runtime
    app_version: {{ .Values.ksocRuntime.reporter.image.tag | quote }}
    maintained_by: ksoc
data:
  ksoc_runtime_profile_rules.yaml: |
  {{- .Values.ksocRuntime.runtimeProfileRules | nindent 4 }}
{{- end }}
