{{- if .Values.ksocRuntime.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: ksoc-runtime
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: ksoc-runtime
    app_version: {{ .Values.ksocRuntime.reporter.image.tag | quote }}
    maintained_by: ksoc
spec:
  selector:
    app_name: ksoc-runtime
    app_version: {{ .Values.ksocRuntime.reporter.image.tag | quote }}
    maintained_by: ksoc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
{{- end -}}
